// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLqz97HQdcqqGNKG_NJEXrU6GCCjTReNM',
    appId: '1:766002223280:web:c65fb78fc10c2ee8958375',
    messagingSenderId: '766002223280',
    projectId: 'e-governance-c9bc6',
    authDomain: 'e-governance-c9bc6.firebaseapp.com',
    storageBucket: 'e-governance-c9bc6.appspot.com',
    measurementId: 'G-K3GBV2NF2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANMfxJIkrOl_V5tLqbYe8AlPKFwc_8EdQ',
    appId: '1:766002223280:android:8cd96b3bccae0663958375',
    messagingSenderId: '766002223280',
    projectId: 'e-governance-c9bc6',
    storageBucket: 'e-governance-c9bc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdNV0la68xxrlPnQoGPOuDVhaqkm-0Xp4',
    appId: '1:766002223280:ios:0506c1be36dcd986958375',
    messagingSenderId: '766002223280',
    projectId: 'e-governance-c9bc6',
    storageBucket: 'e-governance-c9bc6.appspot.com',
    iosClientId: '766002223280-1rqpbn7go36s61en0stk0o8maa4a68f7.apps.googleusercontent.com',
    iosBundleId: 'com.example.egovProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdNV0la68xxrlPnQoGPOuDVhaqkm-0Xp4',
    appId: '1:766002223280:ios:0506c1be36dcd986958375',
    messagingSenderId: '766002223280',
    projectId: 'e-governance-c9bc6',
    storageBucket: 'e-governance-c9bc6.appspot.com',
    iosClientId: '766002223280-1rqpbn7go36s61en0stk0o8maa4a68f7.apps.googleusercontent.com',
    iosBundleId: 'com.example.egovProj',
  );
}
